### ISSUE TITLE
Extension Reverse search feature/search through extension feed

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#381] opened 2024-04-29 08:05 UTC
Please add an option to search the installed managa/Anime extensions and the we can easily match them with ones in Anilist........

![Screenshot_20240429-090056.png](https://github.com/rebelonion/Dantotsu/assets/71634955/d12c5cb7-040d-4cfe-ae30-3d18b9bff853)

![Screenshot_20240429-090112.png](https://github.com/rebelonion/Dantotsu/assets/71634955/7b27e203-89bf-4f77-a5a5-7dcd3b8d160b)

![Screenshot_20240429-090134.png](https://github.com/rebelonion/Dantotsu/assets/71634955/a687ea34-e67c-4042-b1a3-71aa53b57a7c)

**Comment by Mathew20kdroid** [comment] 2024-04-29 08:06
This is from the Dantotsu fork Himitsu

**Comment by Mathew20kdroid** [comment] 2024-04-29 08:33
Am I the only one using light mode😅

**Comment by rebelonion** [comment] 2024-04-29 12:23
Wow that ui is terrible lol

This feature is something I've been undecided about for a while, but leaning more against

**Comment by rebelonion** [comment] 2024-04-29 23:31
duplicate of #356

**Closed by rebelonion** 2024-04-29 23:31 UTC
