### ISSUE TITLE
Problem with extension 

### ISSUE THREAD

**Issue by MRGABOZ** [rebelonion/Dantotsu#21] opened 2023-10-27 11:34 UTC
I have problems with the Legion anime extension. In this extension all the chapters should be shown but only the first chapter appears in all the animes

![Screenshot_20231027_073043_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/fb738af5-12a2-42dc-a684-1bdfda0bee73)
![Screenshot_20231027_073102_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/127360522/e7dfde13-157e-4dea-97b7-d2a9f94e3b3b)

I have also already checked and this problem is not in aniyomi 

![Screenshot_20231027_073131_Animiru](https://github.com/rebelonion/Dantotsu/assets/127360522/ad1f6493-754b-49f6-91bf-fc567c86200f)

Please could you fix that🙏

**Comment by Ainz-23** [comment] 2023-10-27 14:48
Same problem with allanime extensions and some other extensions. Allanime extensions don't have the option to switch between sub and dub. I hope it gets fixed as soon as possible.

**Comment by rebelonion** [comment] 2023-10-27 15:03
> Same problem with allanime extensions and some other extensions. Allanime extensions don't have the option to switch between sub and dub. I hope it gets fixed as soon as possible.

This is not a bug, just a feature that has not been added yet.

**Comment by dinkusoni** [comment] 2023-11-01 13:53
> Same problem with allanime extensions and some other extensions. Allanime extensions don't have the option to switch between sub and dub. I hope it gets fixed as soon as possible.

Dude update Dontutsu now we have dub and sub button in anime episode list

**Comment by rebelonion** [comment] 2023-11-26 18:58
Will be fixed in the next update

**Closed by rebelonion** 2023-11-26 18:58 UTC
