### ISSUE TITLE
App not checking for subscription until it's opened.

### ISSUE THREAD

**Issue by Ykuzhe** [rebelonion/Dantotsu#126] opened 2024-01-14 10:58 UTC
Just like the title says, just for the record. I did set the subscription update frequency to 12 hours and not Don't update lol.

I'm using a Redmi Note 9 and I know the god awful battery saver thing for Xiaomi phones are obnoxious so that could be the main culprit but turning off that and also making Dantotsu autostart in the background does not fix this issue unlike with other apps.

**Comment by rebelonion** [comment] 2024-01-14 18:53
The problem is a little bit of the battery saver, and the notification system is pretty messy in the app. I plan on reworking that whole system.
Duplicate of #66

**Closed by rebelonion** 2024-01-14 18:53 UTC
