### ISSUE TITLE
Download in SD Card option not working 

### ISSUE THREAD

**Issue by KaguyaUchiha** [rebelonion/Dantotsu#206] opened 2024-02-26 09:14 UTC
![Screenshot_20240226-144336_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/112609547/6f481d43-4892-4a93-a1b8-f7399cc64d25)

**Comment by rebelonion** [comment] 2024-02-26 09:21
duplicate of #180

**Closed by rebelonion** 2024-02-26 09:21 UTC
